#!/bin/bash

BUILD_DIR="${PWD}/build"

if [ ! -d "$BUILD_DIR" ]; then
    echo "build directory missing... creating a build directory in $BUILD_DIR"
    mkdir build
fi

cargo run > build/out.ppm
nsxiv build/out.ppm
